from __future__ import annotations

import json
import os
import random
from dataclasses import dataclass
from typing import Any

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from torch.utils.data import Dataset
from torchvision.transforms import functional as TF

from dataloader import HandGestureDataset_v2, SegAugment_v2, mask_to_bbox


CLASS_ID_TO_NAME = {
    0: "call",
    1: "dislike",
    2: "like",
    3: "ok",
    4: "one",
    5: "palm",
    6: "peace",
    7: "rock",
    8: "stop",
    9: "three",
}


@dataclass
class LossWeights:
    cls: float = 1.0
    det_bbox: float = 2.0
    det_obj: float = 0.0
    det_cls: float = 0.5
    seg_bce: float = 1.0
    seg_dice: float = 1.0


class ImageMaskJsonDataset(Dataset):
    """Fallback dataset that reads PNG image/mask pairs from a json index.

    Supports both `image_info.json` and `test_image_info.json` formats generated by
    this repository's preprocessing script.
    """

    def __init__(
        self,
        root_dir: str,
        resize_shape: tuple[int, int] = (256, 256),
        transform: Any | None = None,
    ) -> None:
        self.root_dir = root_dir
        self.resize_shape = resize_shape
        self.transform = transform

        json_path = os.path.join(root_dir, "image_info.json")
        if not os.path.exists(json_path):
            json_path = os.path.join(root_dir, "test_image_info.json")
        if not os.path.exists(json_path):
            raise FileNotFoundError(f"No image_info json found under {root_dir}")

        with open(json_path, "r") as f:
            self.image_info = json.load(f)

        self.image_dir = os.path.join(root_dir, "images")
        self.mask_dir = os.path.join(root_dir, "masks")

    def __len__(self) -> int:
        return len(self.image_info)

    def _load_pair(self, idx: int) -> tuple[torch.Tensor, torch.Tensor, int, torch.Tensor]:
        rec = self.image_info[idx]
        img_name = rec["new_image_name"]
        mask_name = rec["new_mask_name"]

        image = Image.open(os.path.join(self.image_dir, img_name)).convert("RGB")
        mask = Image.open(os.path.join(self.mask_dir, mask_name)).convert("L")

        image_t = TF.to_tensor(image).float()
        mask_t = TF.to_tensor(mask).float()
        mask_t = (mask_t > 0.5).float()

        class_id = int(rec["class_id"])
        bbox = torch.tensor(rec["bbox"], dtype=torch.float32)
        return image_t, mask_t, class_id, bbox

    def __getitem__(self, idx: int):
        image_t, mask_t, class_id, bbox = self._load_pair(idx)

        # Resize first so bbox is always aligned to current tensor size.
        image_t = TF.resize(image_t, self.resize_shape, interpolation=TF.InterpolationMode.BILINEAR)
        mask_t = TF.resize(mask_t, self.resize_shape, interpolation=TF.InterpolationMode.NEAREST)
        bbox = mask_to_bbox(mask_t)

        like_or_dislike = class_id in (1, 2)
        if self.transform is not None:
            image_t, mask_t, bbox = self.transform(image_t, mask_t, bbox, like_or_dislike)

        return image_t, mask_t, torch.tensor([class_id], dtype=torch.long), bbox


def create_dataset(
    root_dir: str,
    resize_shape: tuple[int, int],
    augment: bool,
) -> Dataset:
    """Build a dataset that works for both tensor-backed and image-backed splits."""
    transform = SegAugment_v2(out_size=resize_shape) if augment else None

    has_tensor_dirs = os.path.isdir(os.path.join(root_dir, "image_tensors")) and os.path.isdir(
        os.path.join(root_dir, "mask_tensors")
    )
    has_std_json = os.path.isfile(os.path.join(root_dir, "image_info.json"))

    if has_tensor_dirs and has_std_json:
        return HandGestureDataset_v2(root_dir=root_dir, transform=transform, resize_shape=list(resize_shape))

    return ImageMaskJsonDataset(root_dir=root_dir, resize_shape=resize_shape, transform=transform)


def multitask_collate_fn(batch):
    images, masks, class_ids, bboxes = zip(*batch)
    images = torch.stack(images, dim=0).float()
    masks = torch.stack(masks, dim=0).float()

    if masks.ndim == 3:
        masks = masks.unsqueeze(1)

    class_ids = torch.as_tensor([int(torch.as_tensor(c).view(-1)[0].item()) for c in class_ids], dtype=torch.long)
    bboxes = torch.stack([torch.as_tensor(b, dtype=torch.float32).view(-1)[:4] for b in bboxes], dim=0)
    return images, masks, class_ids, bboxes


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def bbox_cxcywh_to_xyxy(box: torch.Tensor) -> torch.Tensor:
    cx, cy, w, h = box.unbind(-1)
    half_w = w * 0.5
    half_h = h * 0.5
    return torch.stack([cx - half_w, cy - half_h, cx + half_w, cy + half_h], dim=-1)


def box_iou_xyxy(pred: torch.Tensor, target: torch.Tensor, eps: float = 1e-6) -> torch.Tensor:
    ix1 = torch.maximum(pred[..., 0], target[..., 0])
    iy1 = torch.maximum(pred[..., 1], target[..., 1])
    ix2 = torch.minimum(pred[..., 2], target[..., 2])
    iy2 = torch.minimum(pred[..., 3], target[..., 3])

    inter = (ix2 - ix1).clamp(min=0) * (iy2 - iy1).clamp(min=0)
    area_p = (pred[..., 2] - pred[..., 0]).clamp(min=0) * (pred[..., 3] - pred[..., 1]).clamp(min=0)
    area_t = (target[..., 2] - target[..., 0]).clamp(min=0) * (target[..., 3] - target[..., 1]).clamp(min=0)
    return inter / (area_p + area_t - inter + eps)


def complete_box_iou_loss(pred: torch.Tensor, target: torch.Tensor, eps: float = 1e-6) -> torch.Tensor:
    iou = box_iou_xyxy(pred, target, eps=eps)

    pred_cx = (pred[..., 0] + pred[..., 2]) * 0.5
    pred_cy = (pred[..., 1] + pred[..., 3]) * 0.5
    tgt_cx = (target[..., 0] + target[..., 2]) * 0.5
    tgt_cy = (target[..., 1] + target[..., 3]) * 0.5

    center_dist = (pred_cx - tgt_cx).pow(2) + (pred_cy - tgt_cy).pow(2)

    enc_x1 = torch.minimum(pred[..., 0], target[..., 0])
    enc_y1 = torch.minimum(pred[..., 1], target[..., 1])
    enc_x2 = torch.maximum(pred[..., 2], target[..., 2])
    enc_y2 = torch.maximum(pred[..., 3], target[..., 3])
    enc_diag = (enc_x2 - enc_x1).pow(2) + (enc_y2 - enc_y1).pow(2) + eps

    pred_w = (pred[..., 2] - pred[..., 0]).clamp(min=eps)
    pred_h = (pred[..., 3] - pred[..., 1]).clamp(min=eps)
    tgt_w = (target[..., 2] - target[..., 0]).clamp(min=eps)
    tgt_h = (target[..., 3] - target[..., 1]).clamp(min=eps)

    v = (4.0 / (np.pi**2)) * (torch.atan(tgt_w / tgt_h) - torch.atan(pred_w / pred_h)).pow(2)
    alpha = v / (1.0 - iou + v + eps)
    ciou = iou - (center_dist / enc_diag) - alpha * v
    return (1.0 - ciou).mean()


def dice_loss_from_logits(logits: torch.Tensor, target: torch.Tensor, eps: float = 1e-6) -> torch.Tensor:
    probs = torch.sigmoid(logits)
    num = 2.0 * (probs * target).sum(dim=(1, 2, 3))
    den = (probs + target).sum(dim=(1, 2, 3)).clamp(min=eps)
    return (1.0 - num / den).mean()


def dice_score_from_logits(logits: torch.Tensor, target: torch.Tensor, threshold: float = 0.5, eps: float = 1e-6) -> float:
    pred = (torch.sigmoid(logits) >= threshold).float()
    num = 2.0 * (pred * target).sum(dim=(1, 2, 3))
    den = (pred + target).sum(dim=(1, 2, 3)).clamp(min=eps)
    return float((num / den).mean().item())


def decode_det_bbox_to_pixels(det_bbox_raw: torch.Tensor, image_h: int, image_w: int) -> torch.Tensor:
    """Decode detection head bbox logits to absolute pixel cxcywh.

    The current detection head is a linear head without explicit constraints, so we
    apply sigmoid and scale to image space for stable optimization and metrics.
    """
    pred_norm = torch.sigmoid(det_bbox_raw)
    scale = det_bbox_raw.new_tensor([float(image_w), float(image_h), float(image_w), float(image_h)])
    return pred_norm * scale


def compute_multitask_loss(
    outputs: dict[str, Any],
    class_ids: torch.Tensor,
    masks: torch.Tensor,
    bboxes: torch.Tensor,
    image_h: int,
    image_w: int,
    weights: LossWeights,
) -> tuple[torch.Tensor, dict[str, float]]:
    cls_logits = outputs["cls"]
    det = outputs["det"]
    seg_logits = outputs["seg"]

    valid_det_mask = (bboxes[:, 2] > 1.0) & (bboxes[:, 3] > 1.0)

    cls_loss = F.cross_entropy(cls_logits, class_ids, label_smoothing=0.05)

    det_bbox_pred_px = decode_det_bbox_to_pixels(det["bbox"], image_h=image_h, image_w=image_w)
    target_scale = bboxes.new_tensor([float(image_w), float(image_h), float(image_w), float(image_h)])
    det_bbox_target_norm = bboxes / target_scale
    det_bbox_pred_norm = det_bbox_pred_px / target_scale

    pred_xyxy = bbox_cxcywh_to_xyxy(det_bbox_pred_px)
    gt_xyxy = bbox_cxcywh_to_xyxy(bboxes)

    if valid_det_mask.any():
        det_bbox_l1 = F.smooth_l1_loss(det_bbox_pred_norm[valid_det_mask], det_bbox_target_norm[valid_det_mask])
        det_bbox_ciou = complete_box_iou_loss(pred_xyxy[valid_det_mask], gt_xyxy[valid_det_mask])
        det_bbox_loss = det_bbox_l1 + det_bbox_ciou
        det_cls_loss = F.cross_entropy(
            det["class_logits"][valid_det_mask],
            class_ids[valid_det_mask],
            label_smoothing=0.05,
        )
        det_iou = float(box_iou_xyxy(pred_xyxy[valid_det_mask], gt_xyxy[valid_det_mask]).mean().item())
        det_cls_acc = (det["class_logits"][valid_det_mask].argmax(dim=1) == class_ids[valid_det_mask]).float().mean().item()
    else:
        det_bbox_loss = det_bbox_pred_px.sum() * 0.0
        det_cls_loss = det["class_logits"].sum() * 0.0
        det_iou = 0.0
        det_cls_acc = 0.0

    det_obj_target = valid_det_mask.float()
    det_obj_loss = F.binary_cross_entropy_with_logits(det["objectness"].view(-1), det_obj_target)

    seg_bce = F.binary_cross_entropy_with_logits(seg_logits, masks)
    seg_dice = dice_loss_from_logits(seg_logits, masks)

    total = (
        weights.cls * cls_loss
        + weights.det_bbox * det_bbox_loss
        + weights.det_obj * det_obj_loss
        + weights.det_cls * det_cls_loss
        + weights.seg_bce * seg_bce
        + weights.seg_dice * seg_dice
    )

    with torch.no_grad():
        cls_acc = (cls_logits.argmax(dim=1) == class_ids).float().mean().item()
        seg_dice_score = dice_score_from_logits(seg_logits, masks)

    logs = {
        "loss": float(total.item()),
        "loss_cls": float(cls_loss.item()),
        "loss_det_bbox": float(det_bbox_loss.item()),
        "loss_det_obj": float(det_obj_loss.item()),
        "loss_det_cls": float(det_cls_loss.item()),
        "loss_seg_bce": float(seg_bce.item()),
        "loss_seg_dice": float(seg_dice.item()),
        "cls_acc": float(cls_acc),
        "det_cls_acc": float(det_cls_acc),
        "det_iou": float(det_iou),
        "seg_dice": float(seg_dice_score),
    }
    return total, logs


def average_log_dict(logs: list[dict[str, float]]) -> dict[str, float]:
    if len(logs) == 0:
        return {}
    keys = logs[0].keys()
    out = {}
    for k in keys:
        out[k] = float(sum(d[k] for d in logs) / len(logs))
    return out
